spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.246.86:8848
    sentinel:
      transport:
        dashboard: 10.211.55.19:8080 #Sentinel 控制台地址
      eager: true #取消Sentinel控制台懒加载,即项目启动即连接

    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 允许哪些网站的跨域请求
            allowedMethods: "*" # 允许的跨域ajax的请求方式
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360 # 这次跨域检测的有效期
      routes:
        - id: SpringSource
          uri: lb://SpringSource  # 服务端 service_id 实现负载均衡
          # 网关断言匹配
          predicates:
            - Path=/SpringSource/**   # 路由映射路径 这里注意，这个路径会追加到 service_id后
          filters:
#            - StripPrefix=1
            - LogFilter2



  application:
    name: gateway

debug: true
server:
  port: 9999

logging:
  level:
    org.springframework.cloud.gateway: debug

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
