spring:

  cloud:
    nacos:
      discovery:
        server-addr: 101.42.246.86:8848
    sentinel:
      transport:
        dashboard: 10.211.55.19:8080
      #sentinel持久化配置文件
      eager: true #取消Sentinel控制台懒加载,即项目启动即连接
      datasource:
        ds1:
          nacos:
            server-addr: 101.42.246.86:8848
            data-id: SpringSource
            data-type: json
            rule-type: flow

  redis:
      host: 10.211.55.19
      port: 6379
      password: 5201314
      database: 0
  #rabbitmq配置
  rabbitmq:
    host: 10.211.55.19
    password: guest
    port: 5672
    username: guest
    virtual-host: /
    publisher-returns: true #配置消息到达队列的回调。
    # 开启消息确认机制
    publisher-confirm-type: correlated #消息到达交换器的确认回调
    listener:
      simple:
        acknowledge-mode: manual

#  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://10.211.55.19:3306/Demo?characterEncoding=utf8&amp
    username: root


#    加载循环依赖
  main:
    allow-circular-references: true

  application:
    name: SpringSource





#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  sentinel:
    enabled: true


#分页pageHelper
pagehelper:
  helperDialect: mysql #配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  reasonable: true  #配置分页参数合理化功能，默认是false。 #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页； #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
  supportMethodsArguments: true #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  params: count=countSql  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值; 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
  pageSizeZero: true #pageSize=0 or RowBounds.Limit = 0的时候就不适用分页，但是返回对象还是PageInfo







