spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.18:8849
    sentinel:
      transport:
        dashboard: localhost:8480 #Sentinel 控制台地址
      eager: true #取消Sentinel控制台懒加载,即项目启动即连接
      datasource:
        ds1:
          nacos:
            server-addr: 10.211.55.18:8849
            data-id: demo3
            data-type: json
            rule-type: flow
#                        [
#                {
#                  "resource": "/p",
#                  "limitApp": "default",
#                  "grade": 1,
#                  "count": 1,
#                  "strategy": 0,
#                  "controlBehavior": 0,
#                  "clusterMode": false
#                }
#            ]
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 允许哪些网站的跨域请求
            allowedMethods: "*" # 允许的跨域ajax的请求方式
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
        - id: provder
          uri: lb://provder  # 服务端 service_id 实现负载均衡
          # 网关断言匹配
          predicates:
            - Path=/provder/**   # 路由映射路径 这里注意，这个路径会追加到 service_id后

  application:
    name: gateway



debug: true
server:
  port: 9977

logging:
  level:
    org.springframework.cloud.gateway: debug